import { SessionProvider } from "@/components/providers/SessionProvider";
import SideBar from "@/components/SideBar";
import { getServerSession } from "next-auth";
import "@/styles/globals.css";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Login from "@/components/Login";
import ClientProvider from "@/components/providers/ClientProvider";

export const metadata = {
  title: "ChatGpt",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head />
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto mx:min-w-[10rem] mxs:min-w-[10rem]">
                <SideBar />
              </div>
              {/* Client prodvider - Notification */}
              <ClientProvider />
              <div className="bg-[#333640] flex-1">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}

// Web client ID
// 216886350297-7sig87mir4de36cqrj8sola7u16vnge2.apps.googleusercontent.com

// Web client secret
// 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
